package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/devhdn-212/totmaster_api/domain"
	"github.com/devhdn-212/totmaster_api/internal/config"
	"github.com/jackc/pgx/v5"
)

type pasarantotoRepository struct {
	db DBExecutor
}

func NewPasarantotoRepository(db DBExecutor) domain.PasarantotoRepository {
	return &pasarantotoRepository{
		db: db,
	}
}

func (u *pasarantotoRepository) FindAll(ctx context.Context) ([]domain.Pasarantoto, error) {
	query := `SELECT * FROM ` + config.DB_mst_pasaran_togel + ` 
			  ORDER BY GREATEST(create_at, update_at) DESC`

	rows, err := u.db.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// Mapping otomatis ke struct domain.Companyconftoto
	res, err := pgx.CollectRows(rows, pgx.RowToStructByName[domain.Pasarantoto])
	if err != nil {
		return nil, err
	}

	return res, nil
}
func (u *pasarantotoRepository) FindJadwal(ctx context.Context, idpasaran string) ([]domain.Jadwalpasarantoto, error) {
	query := `SELECT * FROM ` + config.DB_mst_pasaran_jadwaltogel + ` 
			  WHERE idpasarantogel = $1  
			  ORDER BY GREATEST(create_at, update_at) DESC`

	rows, err := u.db.Query(ctx, query, idpasaran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// Mapping otomatis ke struct domain.Companyconftoto
	res, err := pgx.CollectRows(rows, pgx.RowToStructByName[domain.Jadwalpasarantoto])
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (u *pasarantotoRepository) FindByID(ctx context.Context, id string) (domain.Pasarantoto, error) {
	var record domain.Pasarantoto
	query := `SELECT idpasarantogel FROM ` + config.DB_mst_pasaran_togel + ` WHERE idpasarantogel = $1 LIMIT 1`

	err := u.db.QueryRow(ctx, query, id).Scan(&record.IDpasarantogel)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.Pasarantoto{}, nil
		}
		return record, err
	}
	return record, nil
}
func (u pasarantotoRepository) FindSelect(ctx context.Context) ([]domain.Pasarantoto, error) {
	query := `SELECT idpasarantogel, nmpasarantogel FROM ` + config.DB_mst_pasaran_togel + ` ORDER BY nmpasarantogel ASC`

	rows, err := u.db.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	res, err := pgx.CollectRows(rows, pgx.RowToStructByNameLax[domain.Pasarantoto])
	if err != nil {
		return nil, err
	}

	return res, nil
}
func (u *pasarantotoRepository) Save(ctx context.Context, pasarantoto *domain.Pasarantoto) error {
	query := `INSERT INTO ` + config.DB_mst_pasaran_togel + ` (
		idpasarantogel,
		nmpasarantogel,
		tipepasaran,
		urlpasaran,
		pasarandiundi,
		pasaranlibur,
		angka_minbasket,
		angka_minbet,
		angka_maxbet4d,
		angka_maxbet3d,
		angka_maxbet3dd,
		angka_maxbet2d,
		angka_maxbet2dd,
		angka_maxbet2dt,
		angka_win4d,
		angka_win3d,
		angka_win3dd,
		angka_win2d,
		angka_win2dd,
		angka_win2dt,
		angka_disc4d,
		angka_disc3d,
		angka_disc3dd,
		angka_disc2d,
		angka_disc2dd,
		angka_disc2dt,
		angka_limitbuang4d,
		angka_limitbuang3d,
		angka_limitbuang3dd,
		angka_limitbuang2d,
		angka_limitbuang2dd,
		angka_limitbuang2dt,
		angka_limittotal4d,
		angka_limittotal3d,
		angka_limittotal3dd,
		angka_limittotal2d,
		angka_limittotal2dd,
		angka_limittotal2dt,
		angka_maxbet4d_full,
		angka_maxbet3d_full,
		angka_maxbet3dd_full,
		angka_maxbet2d_full,
		angka_maxbet2dd_full,
		angka_maxbet2dt_full,
		angka_maxbet4d_bb,
		angka_maxbet3d_bb,
		angka_maxbet3dd_bb,
		angka_maxbet2d_bb,
		angka_maxbet2dd_bb,
		angka_maxbet2dt_bb,
		angka_maxbet4d_bbdisc,
		angka_maxbet3d_bbdisc,
		angka_maxbet3dd_bbdisc,
		angka_maxbet2d_bbdisc,
		angka_maxbet2dd_bbdisc,
		angka_maxbet2dt_bbdisc,
		angka_win4dnodisc,
		angka_win3dnodisc,
		angka_win3ddnodisc,
		angka_win2dnodisc,
		angka_win2ddnodisc,
		angka_win2dtnodisc,
		angka_win4dbb_kena,
		angka_win3dbb_kena,
		angka_win3ddbb_kena,
		angka_win2dbb_kena,
		angka_win2ddbb_kena,
		angka_win2dtbb_kena,
		angka_win4dbb,
		angka_win3dbb,
		angka_win3ddbb,
		angka_win2dbb,
		angka_win2ddbb,
		angka_win2dtbb,
		angka_maxbuy4d,
		angka_maxbuy3d,
		angka_maxbuy3dd,
		angka_maxbuy2d,
		angka_maxbuy2dd,
		angka_maxbuy2dt,
		angka_maxbet4d_fullbb,
		angka_maxbet3d_fullbb,
		angka_maxbet3dd_fullbb,
		angka_maxbet2d_fullbb,
		angka_maxbet2dd_fullbb,
		angka_maxbet2dt_fullbb,
		angka_limitbuang4d_fullbb,
		angka_limitbuang3d_fullbb,
		angka_limitbuang3dd_fullbb,
		angka_limitbuang2d_fullbb,
		angka_limitbuang2dd_fullbb,
		angka_limitbuang2dt_fullbb,
		angka_limittotal4d_fullbb,
		angka_limittotal3d_fullbb,
		angka_limittotal3dd_fullbb,
		angka_limittotal2d_fullbb,
		angka_limittotal2dd_fullbb,
		angka_limittotal2dt_fullbb,
		angka_limitline_4d,
		angka_limitline_3d,
		angka_limitline_2d,
		angka_limitline_2dd,
		angka_limitline_2dt,
		angka_limitline_3dd,
		angka_bbfs,
		cb_minbet,
		cb_maxbet,
		cb_maxbuy,
		cb_win,
		cb_disc,
		cb_limitbuang,
		cb_limitotal,
		cmacau_minbet,
		cmacau_maxbet,
		cmacau_maxbuy,
		cmacau_win2digit,
		cmacau_win3digit,
		cmacau_win4digit,
		cmacau_disc,
		cmacau_limitbuang,
		cmacau_limittotal,
		cnaga_minbet,
		cnaga_maxbet,
		cnaga_maxbuy,
		cnaga_win3digit,
		cnaga_win4digit,
		cnaga_disc,
		cnaga_limitbuang,
		cnaga_limittotal,
		cjitu_minbet,
		cjitu_maxbet,
		cjitu_maxbuy,
		cjitu_winas,
		cjitu_winkop,
		cjitu_winkepala,
		cjitu_winekor,
		cjitu_desic,
		cjitu_limitbuang,
		cjitu_limitotal,
		umum5050_minbet,
		umum5050_maxbet,
		umum5050_maxbuy,
		umum5050_keibesar,
		umum5050_keikecil,
		umum5050_keigenap,
		umum5050_keiganjil,
		umum5050_keitengah,
		umum5050_keitepi,
		umum5050_discbesar,
		umum5050_disckecil,
		umum5050_discgenap,
		umum5050_discganjil,
		umum5050_disctengah,
		umum5050_disctepi,
		umum5050_limitbuang,
		umum5050_limittotal,
		special5050_minbet,
		special5050_maxbet,
		special5050_maxbuy,
		special5050_keiasganjil,
		special5050_keiasgenap,
		special5050_keiasbesar,
		special5050_keiaskecil,
		special5050_keikopganjil,
		special5050_keikopgenap,
		special5050_keikopbesar,
		special5050_keikopkecil,
		special5050_keikepalaganjil,
		special5050_keikepalagenap,
		special5050_keikepalabesar,
		special5050_keikepalakecil,
		special5050_keiekorganjil,
		special5050_keiekorgenap,
		special5050_keiekorbesar,
		special5050_keiekorkecil,
		special5050_discasganjil,
		special5050_discasgenap,
		special5050_discasbesar,
		special5050_discaskecil,
		special5050_disckopganjil,
		special5050_disckopgenap,
		special5050_disckopbesar,
		special5050_disckopkecil,
		special5050_disckepalaganjil,
		special5050_disckepalagenap,
		special5050_disckepalabesar,
		special5050_disckepalakecil,
		special5050_discekorganjil,
		special5050_discekorgenap,
		special5050_discekorbesar,
		special5050_discekorkecil,
		special5050_limitbuang,
		special5050_limittotal,
		kombinasi5050_minbet,
		kombinasi5050_maxbet,
		kombinasi5050_maxbuy,
		kombinasi5050_belakangkeimono,
		kombinasi5050_belakangkeistereo,
		kombinasi5050_belakangkeikembang,
		kombinasi5050_belakangkeikempis,
		kombinasi5050_belakangkeikembar,
		kombinasi5050_tengahkeimono,
		kombinasi5050_tengahkeistereo,
		kombinasi5050_tengahkeikembang,
		kombinasi5050_tengahkeikempis,
		kombinasi5050_tengahkeikembar,
		kombinasi5050_depankeimono,
		kombinasi5050_depankeistereo,
		kombinasi5050_depankeikembang,
		kombinasi5050_depankeikempis,
		kombinasi5050_depankeikembar,
		kombinasi5050_belakangdiscmono,
		kombinasi5050_belakangdiscstereo,
		kombinasi5050_belakangdisckembang,
		kombinasi5050_belakangdisckempis,
		kombinasi5050_belakangdisckembar,
		kombinasi5050_tengahdiscmono,
		kombinasi5050_tengahdiscstereo,
		kombinasi5050_tengahdisckembang,
		kombinasi5050_tengahdisckempis,
		kombinasi5050_tengahdisckembar,
		kombinasi5050_depandiscmono,
		kombinasi5050_depandiscstereo,
		kombinasi5050_depandisckembang,
		kombinasi5050_depandisckempis,
		kombinasi5050_depandisckembar,
		kombinasi5050_limitbuang,
		kombinasi5050_limittotal,
		macaukombinasi_minbet,
		macaukombinasi_maxbet,
		macaukombinasi_maxbuy,
		macaukombinasi_win,
		macaukombinasi_discount,
		macaukombinasi_limitbuang,
		macaukombinasi_limittotal,
		dasar_minbet,
		dasar_maxbet,
		dasar_maxbuy,
		dasar_keibesar,
		dasar_keikecil,
		dasar_keigenap,
		dasar_keiganjil,
		dasar_discbesar,
		dasar_disckecil,
		dasar_discigenap,
		dasar_discganjil,
		dasar_limitbuang,
		dasar_limittotal,
		shio_referal,
		shio_shiotahunini,
		shio_minbet,
		shio_maxbet,
		shio_maxbuy,
		shio_win,
		shio_disc,
		shio_limitbuang,
		shio_limittotal,
		create_by,
		create_at
	) VALUES (
		$1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
		$11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
		$21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
		$31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
		$41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
		$51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
		$61, $62, $63, $64, $65, $66, $67, $68, $69, $70,
		$71, $72, $73, $74, $75, $76, $77, $78, $79, $80,
		$81, $82, $83, $84, $85, $86, $87, $88, $89, $90,
		$91, $92, $93, $94, $95, $96, $97, $98, $99, $100,
		$101, $102, $103, $104, $105, $106, $107, $108, $109, $110,
		$111, $112, $113, $114, $115, $116, $117, $118, $119, $120,
		$121, $122, $123, $124, $125, $126, $127, $128, $129, $130,
		$131, $132, $133, $134, $135, $136, $137, $138, $139, $140,
		$141, $142, $143, $144, $145, $146, $147, $148, $149, $150,
		$151, $152, $153, $154, $155, $156, $157, $158, $159, $160,
		$161, $162, $163, $164, $165, $166, $167, $168, $169, $170,
		$171, $172, $173, $174, $175, $176, $177, $178, $179, $180,
		$181, $182, $183, $184, $185, $186, $187, $188, $189, $190,
		$191, $192, $193, $194, $195, $196, $197, $198, $199, $200,
		$201, $202, $203, $204, $205, $206, $207, $208, $209, $210,
		$211, $212, $213, $214, $215, $216, $217, $218, $219, $220,
		$221, $222, $223, $224, $225, $226, $227, $228, $229, $230,
		$231, $232, $233, $234, $235, $236, $237, $238, $239, $240,
		$241, $242, $243, $244, $245, $246, $247, $248, $249, $250,
		$251, $252, $253, $254, $255, $256, $257, $258, $259
	)`

	_, err := u.db.Exec(ctx, query,
		pasarantoto.IDpasarantogel,
		pasarantoto.Nmpasarantogel,
		pasarantoto.Tipepasaran,
		pasarantoto.URLpasaran,
		pasarantoto.Pasarandiundi,
		pasarantoto.Pasaranlibur,
		pasarantoto.AngkaMinbasket,
		pasarantoto.AngkaMinbet,
		pasarantoto.AngkaMaxbet4d,
		pasarantoto.AngkaMaxbet3d,
		pasarantoto.AngkaMaxbet3dd,
		pasarantoto.AngkaMaxbet2d,
		pasarantoto.AngkaMaxbet2dd,
		pasarantoto.AngkaMaxbet2dt,
		pasarantoto.AngkaWin4d,
		pasarantoto.AngkaWin3d,
		pasarantoto.AngkaWin3dd,
		pasarantoto.AngkaWin2d,
		pasarantoto.AngkaWin2dd,
		pasarantoto.AngkaWin2dt,
		pasarantoto.AngkaDisc4d,
		pasarantoto.AngkaDisc3d,
		pasarantoto.AngkaDisc3dd,
		pasarantoto.AngkaDisc2d,
		pasarantoto.AngkaDisc2dd,
		pasarantoto.AngkaDisc2dt,
		pasarantoto.AngkaLimitbuang4d,
		pasarantoto.AngkaLimitbuang3d,
		pasarantoto.AngkaLimitbuang3dd,
		pasarantoto.AngkaLimitbuang2d,
		pasarantoto.AngkaLimitbuang2dd,
		pasarantoto.AngkaLimitbuang2dt,
		pasarantoto.AngkaLimittotal4d,
		pasarantoto.AngkaLimittotal3d,
		pasarantoto.AngkaLimittotal3dd,
		pasarantoto.AngkaLimittotal2d,
		pasarantoto.AngkaLimittotal2dd,
		pasarantoto.AngkaLimittotal2dt,
		pasarantoto.AngkaMaxbet4dFull,
		pasarantoto.AngkaMaxbet3dFull,
		pasarantoto.AngkaMaxbet3ddFull,
		pasarantoto.AngkaMaxbet2dFull,
		pasarantoto.AngkaMaxbet2ddFull,
		pasarantoto.AngkaMaxbet2dtFull,
		pasarantoto.AngkaMaxbet4dBb,
		pasarantoto.AngkaMaxbet3dBb,
		pasarantoto.AngkaMaxbet3ddBb,
		pasarantoto.AngkaMaxbet2dBb,
		pasarantoto.AngkaMaxbet2ddBb,
		pasarantoto.AngkaMaxbet2dtBb,
		pasarantoto.AngkaMaxbet4dBbdisc,
		pasarantoto.AngkaMaxbet3dBbdisc,
		pasarantoto.AngkaMaxbet3ddBbdisc,
		pasarantoto.AngkaMaxbet2dBbdisc,
		pasarantoto.AngkaMaxbet2ddBbdisc,
		pasarantoto.AngkaMaxbet2dtBbdisc,
		pasarantoto.AngkaWin4dnodisc,
		pasarantoto.AngkaWin3dnodisc,
		pasarantoto.AngkaWin3ddnodisc,
		pasarantoto.AngkaWin2dnodisc,
		pasarantoto.AngkaWin2ddnodisc,
		pasarantoto.AngkaWin2dtnodisc,
		pasarantoto.AngkaWin4dbbKena,
		pasarantoto.AngkaWin3dbbKena,
		pasarantoto.AngkaWin3ddbbKena,
		pasarantoto.AngkaWin2dbbKena,
		pasarantoto.AngkaWin2ddbbKena,
		pasarantoto.AngkaWin2dtbbKena,
		pasarantoto.AngkaWin4dbb,
		pasarantoto.AngkaWin3dbb,
		pasarantoto.AngkaWin3ddbb,
		pasarantoto.AngkaWin2dbb,
		pasarantoto.AngkaWin2ddbb,
		pasarantoto.AngkaWin2dtbb,
		pasarantoto.AngkaMaxbuy4d,
		pasarantoto.AngkaMaxbuy3d,
		pasarantoto.AngkaMaxbuy3dd,
		pasarantoto.AngkaMaxbuy2d,
		pasarantoto.AngkaMaxbuy2dd,
		pasarantoto.AngkaMaxbuy2dt,
		pasarantoto.AngkaMaxbet4dFullbb,
		pasarantoto.AngkaMaxbet3dFullbb,
		pasarantoto.AngkaMaxbet3ddFullbb,
		pasarantoto.AngkaMaxbet2dFullbb,
		pasarantoto.AngkaMaxbet2ddFullbb,
		pasarantoto.AngkaMaxbet2dtFullbb,
		pasarantoto.AngkaLimitbuang4dFullbb,
		pasarantoto.AngkaLimitbuang3dFullbb,
		pasarantoto.AngkaLimitbuang3ddFullbb,
		pasarantoto.AngkaLimitbuang2dFullbb,
		pasarantoto.AngkaLimitbuang2ddFullbb,
		pasarantoto.AngkaLimitbuang2dtFullbb,
		pasarantoto.AngkaLimittotal4dFullbb,
		pasarantoto.AngkaLimittotal3dFullbb,
		pasarantoto.AngkaLimittotal3ddFullbb,
		pasarantoto.AngkaLimittotal2dFullbb,
		pasarantoto.AngkaLimittotal2ddFullbb,
		pasarantoto.AngkaLimittotal2dtFullbb,
		pasarantoto.AngkaLimitline4d,
		pasarantoto.AngkaLimitline3d,
		pasarantoto.AngkaLimitline2d,
		pasarantoto.AngkaLimitline2dd,
		pasarantoto.AngkaLimitline2dt,
		pasarantoto.AngkaLimitline3dd,
		pasarantoto.AngkaBbfs,
		pasarantoto.CbMinbet,
		pasarantoto.CbMaxbet,
		pasarantoto.CbMaxbuy,
		pasarantoto.CbWin,
		pasarantoto.CbDisc,
		pasarantoto.CbLimitbuang,
		pasarantoto.CbLimitotal,
		pasarantoto.CmacauMinbet,
		pasarantoto.CmacauMaxbet,
		pasarantoto.CmacauMaxbuy,
		pasarantoto.CmacauWin2digit,
		pasarantoto.CmacauWin3digit,
		pasarantoto.CmacauWin4digit,
		pasarantoto.CmacauDisc,
		pasarantoto.CmacauLimitbuang,
		pasarantoto.CmacauLimittotal,
		pasarantoto.CnagaMinbet,
		pasarantoto.CnagaMaxbet,
		pasarantoto.CnagaMaxbuy,
		pasarantoto.CnagaWin3digit,
		pasarantoto.CnagaWin4digit,
		pasarantoto.CnagaDisc,
		pasarantoto.CnagaLimitbuang,
		pasarantoto.CnagaLimittotal,
		pasarantoto.CjituMinbet,
		pasarantoto.CjituMaxbet,
		pasarantoto.CjituMaxbuy,
		pasarantoto.CjituWinas,
		pasarantoto.CjituWinkop,
		pasarantoto.CjituWinkepala,
		pasarantoto.CjituWinekor,
		pasarantoto.CjituDesic,
		pasarantoto.CjituLimitbuang,
		pasarantoto.CjituLimitotal,
		pasarantoto.Umum5050Minbet,
		pasarantoto.Umum5050Maxbet,
		pasarantoto.Umum5050Maxbuy,
		pasarantoto.Umum5050Keibesar,
		pasarantoto.Umum5050Keikecil,
		pasarantoto.Umum5050Keigenap,
		pasarantoto.Umum5050Keiganjil,
		pasarantoto.Umum5050Keitengah,
		pasarantoto.Umum5050Keitepi,
		pasarantoto.Umum5050Discbesar,
		pasarantoto.Umum5050Disckecil,
		pasarantoto.Umum5050Discgenap,
		pasarantoto.Umum5050Discganjil,
		pasarantoto.Umum5050Disctengah,
		pasarantoto.Umum5050Disctepi,
		pasarantoto.Umum5050Limitbuang,
		pasarantoto.Umum5050Limittotal,
		pasarantoto.Special5050Minbet,
		pasarantoto.Special5050Maxbet,
		pasarantoto.Special5050Maxbuy,
		pasarantoto.Special5050Keiasganjil,
		pasarantoto.Special5050Keiasgenap,
		pasarantoto.Special5050Keiasbesar,
		pasarantoto.Special5050Keiaskecil,
		pasarantoto.Special5050Keikopganjil,
		pasarantoto.Special5050Keikopgenap,
		pasarantoto.Special5050Keikopbesar,
		pasarantoto.Special5050Keikopkecil,
		pasarantoto.Special5050Keikepalaganjil,
		pasarantoto.Special5050Keikepalagenap,
		pasarantoto.Special5050Keikepalabesar,
		pasarantoto.Special5050Keikepalakecil,
		pasarantoto.Special5050Keiekorganjil,
		pasarantoto.Special5050Keiekorgenap,
		pasarantoto.Special5050Keiekorbesar,
		pasarantoto.Special5050Keiekorkecil,
		pasarantoto.Special5050Discasganjil,
		pasarantoto.Special5050Discasgenap,
		pasarantoto.Special5050Discasbesar,
		pasarantoto.Special5050Discaskecil,
		pasarantoto.Special5050Disckopganjil,
		pasarantoto.Special5050Disckopgenap,
		pasarantoto.Special5050Disckopbesar,
		pasarantoto.Special5050Disckopkecil,
		pasarantoto.Special5050Disckepalaganjil,
		pasarantoto.Special5050Disckepalagenap,
		pasarantoto.Special5050Disckepalabesar,
		pasarantoto.Special5050Disckepalakecil,
		pasarantoto.Special5050Discekorganjil,
		pasarantoto.Special5050Discekorgenap,
		pasarantoto.Special5050Discekorbesar,
		pasarantoto.Special5050Discekorkecil,
		pasarantoto.Special5050Limitbuang,
		pasarantoto.Special5050Limittotal,
		pasarantoto.Kombinasi5050Minbet,
		pasarantoto.Kombinasi5050Maxbet,
		pasarantoto.Kombinasi5050Maxbuy,
		pasarantoto.Kombinasi5050Belakangkeimono,
		pasarantoto.Kombinasi5050Belakangkeistereo,
		pasarantoto.Kombinasi5050Belakangkeikembang,
		pasarantoto.Kombinasi5050Belakangkeikempis,
		pasarantoto.Kombinasi5050Belakangkeikembar,
		pasarantoto.Kombinasi5050Tengahkeimono,
		pasarantoto.Kombinasi5050Tengahkeistereo,
		pasarantoto.Kombinasi5050Tengahkeikembang,
		pasarantoto.Kombinasi5050Tengahkeikempis,
		pasarantoto.Kombinasi5050Tengahkeikembar,
		pasarantoto.Kombinasi5050Depankeimono,
		pasarantoto.Kombinasi5050Depankeistereo,
		pasarantoto.Kombinasi5050Depankeikembang,
		pasarantoto.Kombinasi5050Depankeikempis,
		pasarantoto.Kombinasi5050Depankeikembar,
		pasarantoto.Kombinasi5050Belakangdiscmono,
		pasarantoto.Kombinasi5050Belakangdiscstereo,
		pasarantoto.Kombinasi5050Belakangdisckembang,
		pasarantoto.Kombinasi5050Belakangdisckempis,
		pasarantoto.Kombinasi5050Belakangdisckembar,
		pasarantoto.Kombinasi5050Tengahdiscmono,
		pasarantoto.Kombinasi5050Tengahdiscstereo,
		pasarantoto.Kombinasi5050Tengahdisckembang,
		pasarantoto.Kombinasi5050Tengahdisckempis,
		pasarantoto.Kombinasi5050Tengahdisckembar,
		pasarantoto.Kombinasi5050Depandiscmono,
		pasarantoto.Kombinasi5050Depandiscstereo,
		pasarantoto.Kombinasi5050Depandisckembang,
		pasarantoto.Kombinasi5050Depandisckempis,
		pasarantoto.Kombinasi5050Depandisckembar,
		pasarantoto.Kombinasi5050Limitbuang,
		pasarantoto.Kombinasi5050Limittotal,
		pasarantoto.MacaukombinasiMinbet,
		pasarantoto.MacaukombinasiMaxbet,
		pasarantoto.MacaukombinasiMaxbuy,
		pasarantoto.MacaukombinasiWin,
		pasarantoto.MacaukombinasiDiscount,
		pasarantoto.MacaukombinasiLimitbuang,
		pasarantoto.MacaukombinasiLimittotal,
		pasarantoto.DasarMinbet,
		pasarantoto.DasarMaxbet,
		pasarantoto.DasarMaxbuy,
		pasarantoto.DasarKeibesar,
		pasarantoto.DasarKeikecil,
		pasarantoto.DasarKeigenap,
		pasarantoto.DasarKeiganjil,
		pasarantoto.DasarDiscbesar,
		pasarantoto.DasarDisckecil,
		pasarantoto.DasarDiscigenap,
		pasarantoto.DasarDiscganjil,
		pasarantoto.DasarLimitbuang,
		pasarantoto.DasarLimittotal,
		pasarantoto.ShioReferal,
		pasarantoto.ShioShiotahunini,
		pasarantoto.ShioMinbet,
		pasarantoto.ShioMaxbet,
		pasarantoto.ShioMaxbuy,
		pasarantoto.ShioWin,
		pasarantoto.ShioDisc,
		pasarantoto.ShioLimitbuang,
		pasarantoto.ShioLimittotal,
		pasarantoto.CreateBy,
		pasarantoto.CreateAt,
	)
	return err
}

func (u *pasarantotoRepository) Update(ctx context.Context, pasarantoto *domain.Pasarantoto) error {
	type col struct {
		name string
		val  any
	}

	cols := []col{
		{"nmpasarantogel", pasarantoto.Nmpasarantogel},
		{"tipepasaran", pasarantoto.Tipepasaran},
		{"urlpasaran", pasarantoto.URLpasaran},
		{"pasarandiundi", pasarantoto.Pasarandiundi},
		{"pasaranlibur", pasarantoto.Pasaranlibur},
		{"angka_minbasket", pasarantoto.AngkaMinbasket},
		{"angka_minbet", pasarantoto.AngkaMinbet},
		{"angka_maxbet4d", pasarantoto.AngkaMaxbet4d},
		{"angka_maxbet3d", pasarantoto.AngkaMaxbet3d},
		{"angka_maxbet3dd", pasarantoto.AngkaMaxbet3dd},
		{"angka_maxbet2d", pasarantoto.AngkaMaxbet2d},
		{"angka_maxbet2dd", pasarantoto.AngkaMaxbet2dd},
		{"angka_maxbet2dt", pasarantoto.AngkaMaxbet2dt},
		{"angka_win4d", pasarantoto.AngkaWin4d},
		{"angka_win3d", pasarantoto.AngkaWin3d},
		{"angka_win3dd", pasarantoto.AngkaWin3dd},
		{"angka_win2d", pasarantoto.AngkaWin2d},
		{"angka_win2dd", pasarantoto.AngkaWin2dd},
		{"angka_win2dt", pasarantoto.AngkaWin2dt},
		{"angka_disc4d", pasarantoto.AngkaDisc4d},
		{"angka_disc3d", pasarantoto.AngkaDisc3d},
		{"angka_disc3dd", pasarantoto.AngkaDisc3dd},
		{"angka_disc2d", pasarantoto.AngkaDisc2d},
		{"angka_disc2dd", pasarantoto.AngkaDisc2dd},
		{"angka_disc2dt", pasarantoto.AngkaDisc2dt},
		{"angka_limitbuang4d", pasarantoto.AngkaLimitbuang4d},
		{"angka_limitbuang3d", pasarantoto.AngkaLimitbuang3d},
		{"angka_limitbuang3dd", pasarantoto.AngkaLimitbuang3dd},
		{"angka_limitbuang2d", pasarantoto.AngkaLimitbuang2d},
		{"angka_limitbuang2dd", pasarantoto.AngkaLimitbuang2dd},
		{"angka_limitbuang2dt", pasarantoto.AngkaLimitbuang2dt},
		{"angka_limittotal4d", pasarantoto.AngkaLimittotal4d},
		{"angka_limittotal3d", pasarantoto.AngkaLimittotal3d},
		{"angka_limittotal3dd", pasarantoto.AngkaLimittotal3dd},
		{"angka_limittotal2d", pasarantoto.AngkaLimittotal2d},
		{"angka_limittotal2dd", pasarantoto.AngkaLimittotal2dd},
		{"angka_limittotal2dt", pasarantoto.AngkaLimittotal2dt},
		{"angka_maxbet4d_full", pasarantoto.AngkaMaxbet4dFull},
		{"angka_maxbet3d_full", pasarantoto.AngkaMaxbet3dFull},
		{"angka_maxbet3dd_full", pasarantoto.AngkaMaxbet3ddFull},
		{"angka_maxbet2d_full", pasarantoto.AngkaMaxbet2dFull},
		{"angka_maxbet2dd_full", pasarantoto.AngkaMaxbet2ddFull},
		{"angka_maxbet2dt_full", pasarantoto.AngkaMaxbet2dtFull},
		{"angka_maxbet4d_bb", pasarantoto.AngkaMaxbet4dBb},
		{"angka_maxbet3d_bb", pasarantoto.AngkaMaxbet3dBb},
		{"angka_maxbet3dd_bb", pasarantoto.AngkaMaxbet3ddBb},
		{"angka_maxbet2d_bb", pasarantoto.AngkaMaxbet2dBb},
		{"angka_maxbet2dd_bb", pasarantoto.AngkaMaxbet2ddBb},
		{"angka_maxbet2dt_bb", pasarantoto.AngkaMaxbet2dtBb},
		{"angka_maxbet4d_bbdisc", pasarantoto.AngkaMaxbet4dBbdisc},
		{"angka_maxbet3d_bbdisc", pasarantoto.AngkaMaxbet3dBbdisc},
		{"angka_maxbet3dd_bbdisc", pasarantoto.AngkaMaxbet3ddBbdisc},
		{"angka_maxbet2d_bbdisc", pasarantoto.AngkaMaxbet2dBbdisc},
		{"angka_maxbet2dd_bbdisc", pasarantoto.AngkaMaxbet2ddBbdisc},
		{"angka_maxbet2dt_bbdisc", pasarantoto.AngkaMaxbet2dtBbdisc},
		{"angka_win4dnodisc", pasarantoto.AngkaWin4dnodisc},
		{"angka_win3dnodisc", pasarantoto.AngkaWin3dnodisc},
		{"angka_win3ddnodisc", pasarantoto.AngkaWin3ddnodisc},
		{"angka_win2dnodisc", pasarantoto.AngkaWin2dnodisc},
		{"angka_win2ddnodisc", pasarantoto.AngkaWin2ddnodisc},
		{"angka_win2dtnodisc", pasarantoto.AngkaWin2dtnodisc},
		{"angka_win4dbb_kena", pasarantoto.AngkaWin4dbbKena},
		{"angka_win3dbb_kena", pasarantoto.AngkaWin3dbbKena},
		{"angka_win3ddbb_kena", pasarantoto.AngkaWin3ddbbKena},
		{"angka_win2dbb_kena", pasarantoto.AngkaWin2dbbKena},
		{"angka_win2ddbb_kena", pasarantoto.AngkaWin2ddbbKena},
		{"angka_win2dtbb_kena", pasarantoto.AngkaWin2dtbbKena},
		{"angka_win4dbb", pasarantoto.AngkaWin4dbb},
		{"angka_win3dbb", pasarantoto.AngkaWin3dbb},
		{"angka_win3ddbb", pasarantoto.AngkaWin3ddbb},
		{"angka_win2dbb", pasarantoto.AngkaWin2dbb},
		{"angka_win2ddbb", pasarantoto.AngkaWin2ddbb},
		{"angka_win2dtbb", pasarantoto.AngkaWin2dtbb},
		{"angka_maxbuy4d", pasarantoto.AngkaMaxbuy4d},
		{"angka_maxbuy3d", pasarantoto.AngkaMaxbuy3d},
		{"angka_maxbuy3dd", pasarantoto.AngkaMaxbuy3dd},
		{"angka_maxbuy2d", pasarantoto.AngkaMaxbuy2d},
		{"angka_maxbuy2dd", pasarantoto.AngkaMaxbuy2dd},
		{"angka_maxbuy2dt", pasarantoto.AngkaMaxbuy2dt},
		{"angka_maxbet4d_fullbb", pasarantoto.AngkaMaxbet4dFullbb},
		{"angka_maxbet3d_fullbb", pasarantoto.AngkaMaxbet3dFullbb},
		{"angka_maxbet3dd_fullbb", pasarantoto.AngkaMaxbet3ddFullbb},
		{"angka_maxbet2d_fullbb", pasarantoto.AngkaMaxbet2dFullbb},
		{"angka_maxbet2dd_fullbb", pasarantoto.AngkaMaxbet2ddFullbb},
		{"angka_maxbet2dt_fullbb", pasarantoto.AngkaMaxbet2dtFullbb},
		{"angka_limitbuang4d_fullbb", pasarantoto.AngkaLimitbuang4dFullbb},
		{"angka_limitbuang3d_fullbb", pasarantoto.AngkaLimitbuang3dFullbb},
		{"angka_limitbuang3dd_fullbb", pasarantoto.AngkaLimitbuang3ddFullbb},
		{"angka_limitbuang2d_fullbb", pasarantoto.AngkaLimitbuang2dFullbb},
		{"angka_limitbuang2dd_fullbb", pasarantoto.AngkaLimitbuang2ddFullbb},
		{"angka_limitbuang2dt_fullbb", pasarantoto.AngkaLimitbuang2dtFullbb},
		{"angka_limittotal4d_fullbb", pasarantoto.AngkaLimittotal4dFullbb},
		{"angka_limittotal3d_fullbb", pasarantoto.AngkaLimittotal3dFullbb},
		{"angka_limittotal3dd_fullbb", pasarantoto.AngkaLimittotal3ddFullbb},
		{"angka_limittotal2d_fullbb", pasarantoto.AngkaLimittotal2dFullbb},
		{"angka_limittotal2dd_fullbb", pasarantoto.AngkaLimittotal2ddFullbb},
		{"angka_limittotal2dt_fullbb", pasarantoto.AngkaLimittotal2dtFullbb},
		{"angka_limitline_4d", pasarantoto.AngkaLimitline4d},
		{"angka_limitline_3d", pasarantoto.AngkaLimitline3d},
		{"angka_limitline_2d", pasarantoto.AngkaLimitline2d},
		{"angka_limitline_2dd", pasarantoto.AngkaLimitline2dd},
		{"angka_limitline_2dt", pasarantoto.AngkaLimitline2dt},
		{"angka_limitline_3dd", pasarantoto.AngkaLimitline3dd},
		{"angka_bbfs", pasarantoto.AngkaBbfs},
		{"cb_minbet", pasarantoto.CbMinbet},
		{"cb_maxbet", pasarantoto.CbMaxbet},
		{"cb_maxbuy", pasarantoto.CbMaxbuy},
		{"cb_win", pasarantoto.CbWin},
		{"cb_disc", pasarantoto.CbDisc},
		{"cb_limitbuang", pasarantoto.CbLimitbuang},
		{"cb_limitotal", pasarantoto.CbLimitotal},
		{"cmacau_minbet", pasarantoto.CmacauMinbet},
		{"cmacau_maxbet", pasarantoto.CmacauMaxbet},
		{"cmacau_maxbuy", pasarantoto.CmacauMaxbuy},
		{"cmacau_win2digit", pasarantoto.CmacauWin2digit},
		{"cmacau_win3digit", pasarantoto.CmacauWin3digit},
		{"cmacau_win4digit", pasarantoto.CmacauWin4digit},
		{"cmacau_disc", pasarantoto.CmacauDisc},
		{"cmacau_limitbuang", pasarantoto.CmacauLimitbuang},
		{"cmacau_limittotal", pasarantoto.CmacauLimittotal},
		{"cnaga_minbet", pasarantoto.CnagaMinbet},
		{"cnaga_maxbet", pasarantoto.CnagaMaxbet},
		{"cnaga_maxbuy", pasarantoto.CnagaMaxbuy},
		{"cnaga_win3digit", pasarantoto.CnagaWin3digit},
		{"cnaga_win4digit", pasarantoto.CnagaWin4digit},
		{"cnaga_disc", pasarantoto.CnagaDisc},
		{"cnaga_limitbuang", pasarantoto.CnagaLimitbuang},
		{"cnaga_limittotal", pasarantoto.CnagaLimittotal},
		{"cjitu_minbet", pasarantoto.CjituMinbet},
		{"cjitu_maxbet", pasarantoto.CjituMaxbet},
		{"cjitu_maxbuy", pasarantoto.CjituMaxbuy},
		{"cjitu_winas", pasarantoto.CjituWinas},
		{"cjitu_winkop", pasarantoto.CjituWinkop},
		{"cjitu_winkepala", pasarantoto.CjituWinkepala},
		{"cjitu_winekor", pasarantoto.CjituWinekor},
		{"cjitu_desic", pasarantoto.CjituDesic},
		{"cjitu_limitbuang", pasarantoto.CjituLimitbuang},
		{"cjitu_limitotal", pasarantoto.CjituLimitotal},
		{"umum5050_minbet", pasarantoto.Umum5050Minbet},
		{"umum5050_maxbet", pasarantoto.Umum5050Maxbet},
		{"umum5050_maxbuy", pasarantoto.Umum5050Maxbuy},
		{"umum5050_keibesar", pasarantoto.Umum5050Keibesar},
		{"umum5050_keikecil", pasarantoto.Umum5050Keikecil},
		{"umum5050_keigenap", pasarantoto.Umum5050Keigenap},
		{"umum5050_keiganjil", pasarantoto.Umum5050Keiganjil},
		{"umum5050_keitengah", pasarantoto.Umum5050Keitengah},
		{"umum5050_keitepi", pasarantoto.Umum5050Keitepi},
		{"umum5050_discbesar", pasarantoto.Umum5050Discbesar},
		{"umum5050_disckecil", pasarantoto.Umum5050Disckecil},
		{"umum5050_discgenap", pasarantoto.Umum5050Discgenap},
		{"umum5050_discganjil", pasarantoto.Umum5050Discganjil},
		{"umum5050_disctengah", pasarantoto.Umum5050Disctengah},
		{"umum5050_disctepi", pasarantoto.Umum5050Disctepi},
		{"umum5050_limitbuang", pasarantoto.Umum5050Limitbuang},
		{"umum5050_limittotal", pasarantoto.Umum5050Limittotal},
		{"special5050_minbet", pasarantoto.Special5050Minbet},
		{"special5050_maxbet", pasarantoto.Special5050Maxbet},
		{"special5050_maxbuy", pasarantoto.Special5050Maxbuy},
		{"special5050_keiasganjil", pasarantoto.Special5050Keiasganjil},
		{"special5050_keiasgenap", pasarantoto.Special5050Keiasgenap},
		{"special5050_keiasbesar", pasarantoto.Special5050Keiasbesar},
		{"special5050_keiaskecil", pasarantoto.Special5050Keiaskecil},
		{"special5050_keikopganjil", pasarantoto.Special5050Keikopganjil},
		{"special5050_keikopgenap", pasarantoto.Special5050Keikopgenap},
		{"special5050_keikopbesar", pasarantoto.Special5050Keikopbesar},
		{"special5050_keikopkecil", pasarantoto.Special5050Keikopkecil},
		{"special5050_keikepalaganjil", pasarantoto.Special5050Keikepalaganjil},
		{"special5050_keikepalagenap", pasarantoto.Special5050Keikepalagenap},
		{"special5050_keikepalabesar", pasarantoto.Special5050Keikepalabesar},
		{"special5050_keikepalakecil", pasarantoto.Special5050Keikepalakecil},
		{"special5050_keiekorganjil", pasarantoto.Special5050Keiekorganjil},
		{"special5050_keiekorgenap", pasarantoto.Special5050Keiekorgenap},
		{"special5050_keiekorbesar", pasarantoto.Special5050Keiekorbesar},
		{"special5050_keiekorkecil", pasarantoto.Special5050Keiekorkecil},
		{"special5050_discasganjil", pasarantoto.Special5050Discasganjil},
		{"special5050_discasgenap", pasarantoto.Special5050Discasgenap},
		{"special5050_discasbesar", pasarantoto.Special5050Discasbesar},
		{"special5050_discaskecil", pasarantoto.Special5050Discaskecil},
		{"special5050_disckopganjil", pasarantoto.Special5050Disckopganjil},
		{"special5050_disckopgenap", pasarantoto.Special5050Disckopgenap},
		{"special5050_disckopbesar", pasarantoto.Special5050Disckopbesar},
		{"special5050_disckopkecil", pasarantoto.Special5050Disckopkecil},
		{"special5050_disckepalaganjil", pasarantoto.Special5050Disckepalaganjil},
		{"special5050_disckepalagenap", pasarantoto.Special5050Disckepalagenap},
		{"special5050_disckepalabesar", pasarantoto.Special5050Disckepalabesar},
		{"special5050_disckepalakecil", pasarantoto.Special5050Disckepalakecil},
		{"special5050_discekorganjil", pasarantoto.Special5050Discekorganjil},
		{"special5050_discekorgenap", pasarantoto.Special5050Discekorgenap},
		{"special5050_discekorbesar", pasarantoto.Special5050Discekorbesar},
		{"special5050_discekorkecil", pasarantoto.Special5050Discekorkecil},
		{"special5050_limitbuang", pasarantoto.Special5050Limitbuang},
		{"special5050_limittotal", pasarantoto.Special5050Limittotal},
		{"kombinasi5050_minbet", pasarantoto.Kombinasi5050Minbet},
		{"kombinasi5050_maxbet", pasarantoto.Kombinasi5050Maxbet},
		{"kombinasi5050_maxbuy", pasarantoto.Kombinasi5050Maxbuy},
		{"kombinasi5050_belakangkeimono", pasarantoto.Kombinasi5050Belakangkeimono},
		{"kombinasi5050_belakangkeistereo", pasarantoto.Kombinasi5050Belakangkeistereo},
		{"kombinasi5050_belakangkeikembang", pasarantoto.Kombinasi5050Belakangkeikembang},
		{"kombinasi5050_belakangkeikempis", pasarantoto.Kombinasi5050Belakangkeikempis},
		{"kombinasi5050_belakangkeikembar", pasarantoto.Kombinasi5050Belakangkeikembar},
		{"kombinasi5050_tengahkeimono", pasarantoto.Kombinasi5050Tengahkeimono},
		{"kombinasi5050_tengahkeistereo", pasarantoto.Kombinasi5050Tengahkeistereo},
		{"kombinasi5050_tengahkeikembang", pasarantoto.Kombinasi5050Tengahkeikembang},
		{"kombinasi5050_tengahkeikempis", pasarantoto.Kombinasi5050Tengahkeikempis},
		{"kombinasi5050_tengahkeikembar", pasarantoto.Kombinasi5050Tengahkeikembar},
		{"kombinasi5050_depankeimono", pasarantoto.Kombinasi5050Depankeimono},
		{"kombinasi5050_depankeistereo", pasarantoto.Kombinasi5050Depankeistereo},
		{"kombinasi5050_depankeikembang", pasarantoto.Kombinasi5050Depankeikembang},
		{"kombinasi5050_depankeikempis", pasarantoto.Kombinasi5050Depankeikempis},
		{"kombinasi5050_depankeikembar", pasarantoto.Kombinasi5050Depankeikembar},
		{"kombinasi5050_belakangdiscmono", pasarantoto.Kombinasi5050Belakangdiscmono},
		{"kombinasi5050_belakangdiscstereo", pasarantoto.Kombinasi5050Belakangdiscstereo},
		{"kombinasi5050_belakangdisckembang", pasarantoto.Kombinasi5050Belakangdisckembang},
		{"kombinasi5050_belakangdisckempis", pasarantoto.Kombinasi5050Belakangdisckempis},
		{"kombinasi5050_belakangdisckembar", pasarantoto.Kombinasi5050Belakangdisckembar},
		{"kombinasi5050_tengahdiscmono", pasarantoto.Kombinasi5050Tengahdiscmono},
		{"kombinasi5050_tengahdiscstereo", pasarantoto.Kombinasi5050Tengahdiscstereo},
		{"kombinasi5050_tengahdisckembang", pasarantoto.Kombinasi5050Tengahdisckembang},
		{"kombinasi5050_tengahdisckempis", pasarantoto.Kombinasi5050Tengahdisckempis},
		{"kombinasi5050_tengahdisckembar", pasarantoto.Kombinasi5050Tengahdisckembar},
		{"kombinasi5050_depandiscmono", pasarantoto.Kombinasi5050Depandiscmono},
		{"kombinasi5050_depandiscstereo", pasarantoto.Kombinasi5050Depandiscstereo},
		{"kombinasi5050_depandisckembang", pasarantoto.Kombinasi5050Depandisckembang},
		{"kombinasi5050_depandisckempis", pasarantoto.Kombinasi5050Depandisckempis},
		{"kombinasi5050_depandisckembar", pasarantoto.Kombinasi5050Depandisckembar},
		{"kombinasi5050_limitbuang", pasarantoto.Kombinasi5050Limitbuang},
		{"kombinasi5050_limittotal", pasarantoto.Kombinasi5050Limittotal},
		{"macaukombinasi_minbet", pasarantoto.MacaukombinasiMinbet},
		{"macaukombinasi_maxbet", pasarantoto.MacaukombinasiMaxbet},
		{"macaukombinasi_maxbuy", pasarantoto.MacaukombinasiMaxbuy},
		{"macaukombinasi_win", pasarantoto.MacaukombinasiWin},
		{"macaukombinasi_discount", pasarantoto.MacaukombinasiDiscount},
		{"macaukombinasi_limitbuang", pasarantoto.MacaukombinasiLimitbuang},
		{"macaukombinasi_limittotal", pasarantoto.MacaukombinasiLimittotal},
		{"dasar_minbet", pasarantoto.DasarMinbet},
		{"dasar_maxbet", pasarantoto.DasarMaxbet},
		{"dasar_maxbuy", pasarantoto.DasarMaxbuy},
		{"dasar_keibesar", pasarantoto.DasarKeibesar},
		{"dasar_keikecil", pasarantoto.DasarKeikecil},
		{"dasar_keigenap", pasarantoto.DasarKeigenap},
		{"dasar_keiganjil", pasarantoto.DasarKeiganjil},
		{"dasar_discbesar", pasarantoto.DasarDiscbesar},
		{"dasar_disckecil", pasarantoto.DasarDisckecil},
		{"dasar_discigenap", pasarantoto.DasarDiscigenap},
		{"dasar_discganjil", pasarantoto.DasarDiscganjil},
		{"dasar_limitbuang", pasarantoto.DasarLimitbuang},
		{"dasar_limittotal", pasarantoto.DasarLimittotal},
		{"shio_referal", pasarantoto.ShioReferal},
		{"shio_shiotahunini", pasarantoto.ShioShiotahunini},
		{"shio_minbet", pasarantoto.ShioMinbet},
		{"shio_maxbet", pasarantoto.ShioMaxbet},
		{"shio_maxbuy", pasarantoto.ShioMaxbuy},
		{"shio_win", pasarantoto.ShioWin},
		{"shio_disc", pasarantoto.ShioDisc},
		{"shio_limitbuang", pasarantoto.ShioLimitbuang},
		{"shio_limittotal", pasarantoto.ShioLimittotal},
		{"update_by", pasarantoto.UpdateBy},
		{"update_at", pasarantoto.UpdateAt},
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)
	for i, cl := range cols {
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", cl.name, i+1))
		args = append(args, cl.val)
	}

	query := fmt.Sprintf(`UPDATE %s SET %s WHERE idpasarantogel = $%d`,
		config.DB_mst_pasaran_togel,
		strings.Join(setClauses, ", "),
		len(cols)+1,
	)
	args = append(args, pasarantoto.IDpasarantogel)

	res, err := u.db.Exec(ctx, query, args...)
	if err != nil {
		return err
	}
	if res.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}
	return nil
}
func (u *pasarantotoRepository) Savejadwal(ctx context.Context, jadwal *domain.Jadwalpasarantoto) error {
	query := `INSERT INTO ` + config.DB_mst_pasaran_jadwaltogel + ` (
		idjadwalpasarantogel,
		idpasarantogel,
		haripasaran,
		jamtutup,
		jamjadwal,
		jamopen,
		create_by,
		create_at
	) VALUES (
		$1, $2, $3, $4, $5, $6, $7, $8
	)`

	_, err := u.db.Exec(ctx, query,
		jadwal.IDjadwalpasarantogel,
		jadwal.IDpasarantogel,
		jadwal.Haripasaran,
		jadwal.Jamtutup,
		jadwal.Jamjadwal,
		jadwal.Jamopen,
		jadwal.CreateBy,
		jadwal.CreateAt,
	)
	return err
}
func (u *pasarantotoRepository) Updatejadwal(ctx context.Context, jadwal *domain.Jadwalpasarantoto) error {
	type col struct {
		name string
		val  any
	}

	cols := []col{
		{"haripasaran", jadwal.Haripasaran},
		{"jamtutup", jadwal.Jamtutup},
		{"jamjadwal", jadwal.Jamjadwal},
		{"jamopen", jadwal.Jamopen},
		{"update_by", jadwal.UpdateBy},
		{"update_at", jadwal.UpdateAt},
	}

	setClauses := make([]string, 0, len(cols))
	args := make([]any, 0, len(cols)+1)
	for i, cl := range cols {
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", cl.name, i+1))
		args = append(args, cl.val)
	}

	query := fmt.Sprintf(`UPDATE %s SET %s WHERE idjadwalpasarantogel = $%d`,
		config.DB_mst_pasaran_jadwaltogel,
		strings.Join(setClauses, ", "),
		len(cols)+1,
	)
	args = append(args, jadwal.IDjadwalpasarantogel)

	res, err := u.db.Exec(ctx, query, args...)
	if err != nil {
		return err
	}
	if res.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}
	return nil
}
func (u *pasarantotoRepository) DeleteJadwalByPasaran(ctx context.Context, idpasarantogel string) error {
	query := `DELETE FROM ` + config.DB_mst_pasaran_jadwaltogel + ` WHERE idpasarantogel = $1`
	_, err := u.db.Exec(ctx, query, idpasarantogel)
	return err
}
